version: '3.8'

# This Docker Compose file is for running the database service only.
# To run: docker-compose  up -d
# To stop: docker-compose -f docker-compose.db.yml down

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
#    platform: linux/arm64
    container_name: tnai-db-local
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password123
    ports:
      - "1433:1433"
    volumes:
      - tnai-db-data:/var/opt/mssql

volumes:
  tnai-db-data:
    driver: local